using System.ComponentModel.DataAnnotations;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;

namespace MvcBankingApplication.Models.Users
{
    abstract public class UserModel
    {
        private string _password = String.Empty;

        public int ID { get; set; }
        public string ImageUrl { get; set; } = "/images/avatar.png";

        [Required]
        [StringLength(50, MinimumLength = 8)]
        [RegularExpression(
            @"([@_!#$%^&*()<>?/|}{~:]|[0-9])+.*([@_!#$%^&*()<>?/|}{~:]|[0-9])+",
            ErrorMessage = "Password must contain at least one number(zero through nine)" +
            " and one special character(@, _, !, #, $, %, ^, &, *, (, )," +
            " <, >, ?, /, |, }, {, ~, :)"
        )]
        public string Password
        {
            get { return _password; }
            set
            {
                _password = EncryptPassword(value);
            }
        }
        [Required]
        [RegularExpression(@"[a-zA-Z]{2,20}")]
        public string Username { get; set; } = String.Empty;
        [Required]
        [RegularExpression(@"[a-zA-Z]{2,10}")]
        public string FirstName { get; set; } = String.Empty;
        [Required]
        [RegularExpression(@"[a-zA-Z]{2,10}")]
        public string LastName { get; set; } = String.Empty;
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; } = String.Empty;

        /**
         * <summary>
         * generates a password hash
         * </summary>
         */
        public static string EncryptPassword(string password, byte[] salt = null)
        {
            if (salt == null)
            {
                salt = GenerateSalt(128);
            }
            byte[] hashedPassBytes = KeyDerivation.Pbkdf2(
                salt: salt, password: password,
                prf: KeyDerivationPrf.HMACSHA256, numBytesRequested: 256 / 8,
                iterationCount: 10000);
            string passwordHashStr = Convert.ToBase64String(hashedPassBytes);
            string saltStr = Convert.ToBase64String(salt);
            return $"{saltStr}:{passwordHashStr}";
        }

        /**
         * <summary>
         * authenticates a password
         * </summary>
         *
         * <returns>
         * true if the password is correct.
         * false if the password is incorrect.
         * </returns>
         */
        public static bool VerifyPassword(string password, string hash)
        {
            string[] saltAndHash = hash.Split(':');
            if (saltAndHash.Length != 2)
                return false;
            string salt = saltAndHash[0];
            if (salt == null)
                return false;
            byte[] saltBytes = Convert.FromBase64String(salt);
            string calculatedHash = EncryptPassword(password, saltBytes);
            return (String.Compare(hash, calculatedHash) == 0);
        }

        /**
         * <summary>
         * generates a random salt in form of a byte array
         * </summary>
         *
         * <returns>
         * an array of randomly generated bytes
         * </returns>
         */
        private static byte[] GenerateSalt(int numBits)
        {
            byte[] newSalt = new byte[numBits / 8];
            // fill up salt array with random bytes
            using (RandomNumberGenerator rng = RandomNumberGenerator.Create())
            {
                rng.GetBytes(newSalt);
                return newSalt;
            }
        }

        public override string ToString()
        {
            return $"Username<{Username}>; FirstName<{FirstName}>;" +
            $" LastName<{LastName}>; Password<{Password}>";
        }
    }
}
